### ISSUE TITLE
Faild to generate Swift bindings

### ISSUE THREAD

**Issue by Yorik0512** [sicpa-dlab/didcomm-rust#70] opened 2022-06-21 12:25 UTC
Hi Guys,

I'm trying to run uniffi wrapper for swift as by this guide (https://github.com/sicpa-dlab/didcomm-rust/blob/main/uniffi/README.md).

But I catched an error in "3. Generate Swift binding:" point when I run command: `uniffi-bindgen generate src/didcomm.udl --language swift -o ../wrappers/swift/didcomm`

Error body: 
```
Error: Failed to parse UDL

Caused by:
    ExtendedAttributeNoArgs not supported: "Wrapped"

```

Could you please advice on what could be the problem?

P.S.: I'm trying to use swift code from [wrappers](https://github.com/sicpa-dlab/didcomm-rust/tree/main/wrappers/swift/) but unfortunately README.md file is empty. Could you share some more details on how I can work with the given module?

Thank you in advance,
Yurii

**Comment by yvgny** [comment] 2022-11-23 15:53
Hi @Yorik0512, sorry for the late answer.

This problem occurred because the version of the `uniffi-bindgen` binary did not match the one of the library.

So this command:
```bash
cargo install uniffi-bindgen
```
should instead be (as of now)
```bash
cargo install uniffi-bindgen --version 0.15.2
```

I updated the `README.md` to reflect this (see #96). Thanks for noticing the problem and submitting an issue!

I'll close the issue as I could reproduce the issue and this fix solved it, but feel free to re-open it if you still encounter problems.

Sacha

**Closed** 2022-12-01 16:01 UTC
